# Generated by Django 5.2.7 on 2025-11-12 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_options_feedback_metadata_and_more'),
        ('issues', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='1=Low, 2=Medium, 3=High'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'priority'], name='issues_status_88878d_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created_at'], name='issues_created_febe30_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['updated_at'], name='issues_updated_5625e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 3)), name='issues_priority_between_1_and_3'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_progress', 'resolved'])), name='issues_status_valid'),
        ),
        migrations.AlterModelTable(
            name='issue',
            table='issues',
        ),
    ]
